apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: stage
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
      - name: wait-for-mysql
        image: busybox:1.28
        command: ['sh', '-c', 'until nc -z mysql-service.stage.svc.cluster.local 3306; do echo "Waiting for MySQL..."; sleep 5; done']
        envFrom:
        - secretRef:
            name: mysql-secret
      containers:
      - name: backend
        image: us-central1-docker.pkg.dev/extrapm3/repoextra/backend:latest
        ports:
        - containerPort: 5000
          name: http
        envFrom:
        - configMapRef:
            name: mysql-config
        - secretRef:
            name: mysql-secret
        env:
        - name: DB_HOST
          value: "mysql-service.stage.svc.cluster.local"
        - name: DB_PORT
          value: "3306"
        readinessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 45
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            cpu: "10m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 15"]