apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: us-central1-docker.pkg.dev/extrapm3/repoextra/frontend:latest
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /          # Rota raiz ou /health (depende do seu frontend)
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 10
        resources:
          requests:
            cpu: "50m"      # Frontend geralmente consome menos CPU
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"