apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: stage
  labels:
    app: mysql
spec:
  clusterIP: None  # Headless service para StatefulSet
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
  selector:
    app: mysql