name: Build and Deploy
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Autenticar no Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1    
    
    - name: Configure Docker
      run: gcloud auth configure-docker us-central1-docker.pkg.dev
    
    - name: Build and Push Backend
      working-directory: ./backend
      run: |
        docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/repoextra/backend:latest .
        docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/repoextra/backend:latest
    
    - name: Build and Push Frontend
      working-directory: ./frontend
      run: |
        docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/repoextra/frontend:latest .
        docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/repoextra/frontend:latest

    - name: Install gke-gcloud-auth-plugin
      run: |
 
        echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
    
    
        curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
    
   
        sudo apt-get update && sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin
    
    - name: Get Cluster Credentials
      run: |
        gcloud container clusters get-credentials cluster-extrapm3-${{ vars.CLUSTER_SUFFIX }} \
        --zone us-central1-a \
        --project ${{ secrets.GCP_PROJECT }}
        kubectl config current-context

    - name: Apply Kubernetes configurations
      run: |
        kubectl apply -f mysql-config.yaml
        kubectl apply -f mysql-deployment.yaml
        kubectl apply -f backend-deployment.yaml
        kubectl apply -f backend-service.yaml
        kubectl apply -f frontend-deployment.yaml
        kubectl apply -f frontend-service.yaml 